[theme]
base = "dark"
primaryColor = "#00F5A0"
backgroundColor = "#07090E"
secondaryBackgroundColor = "#0F141E"
textColor = "#FFFFFF"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
